---
- name: setup_docker
  hosts: dockerhost
  roles:
    - williamyeh.oracle-java
  vars:
    java_version: 8
    java_download_from_oracle: true
    java_remove_download: true
    java_set_javahome: false
    java_install_jce: false
    # execute all commands as root
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: true
