# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # build docker on this box
  config.vm.box = "tknerr/baseimage-ubuntu-16.04"
  config.vm.box_version = "1.0.0"
  
  # port forwarding from host to VM
  [ "4243","4440","3306","8081","8082","9000"].each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
  end
  
  # use a private network for VMs to communicate
  config.vm.network "private_network", ip: "192.168.33.10"

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # docker customizaations and settings
  config.vm.provider "docker" do |d|
    d.name = "ansiblebox"
  end

  # provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install software-properties-common -y > /dev/null 2>&1
    apt-add-repository ppa:ansible/ansible
    apt-get install ansible -y > /dev/null 2>&1
  SHELL
  
  config.vm.provision "ansible" do |ansible|
    # install galaxy role
    ansible.galaxy_role_file = '../../requirements.yml'
    ansible.playbook = "../../playbook.yml"
	ansible.verbose = "vvv"
  end
end
